//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Food.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EFood : DbContext
    {
        public EFood()
            : base("name=EFood")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detalle_Orden> Detalle_Orden { get; set; }
        public virtual DbSet<Mesa> Mesas { get; set; }
        public virtual DbSet<Orden> Ordens { get; set; }
        public virtual DbSet<Servicio> Servicios { get; set; }
        public virtual DbSet<TipoAB> TipoABs { get; set; }
        public virtual DbSet<TipoServicio> TipoServicios { get; set; }
    
        public virtual int borrarDetalleOrden(Nullable<int> idOrden, Nullable<int> idServicio)
        {
            var idOrdenParameter = idOrden.HasValue ?
                new ObjectParameter("idOrden", idOrden) :
                new ObjectParameter("idOrden", typeof(int));
    
            var idServicioParameter = idServicio.HasValue ?
                new ObjectParameter("idServicio", idServicio) :
                new ObjectParameter("idServicio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("borrarDetalleOrden", idOrdenParameter, idServicioParameter);
        }
    
        public virtual int borrarMesa(Nullable<int> idMesa)
        {
            var idMesaParameter = idMesa.HasValue ?
                new ObjectParameter("idMesa", idMesa) :
                new ObjectParameter("idMesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("borrarMesa", idMesaParameter);
        }
    
        public virtual int borrarOrden(Nullable<int> idOrden)
        {
            var idOrdenParameter = idOrden.HasValue ?
                new ObjectParameter("idOrden", idOrden) :
                new ObjectParameter("idOrden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("borrarOrden", idOrdenParameter);
        }
    
        public virtual int borrarServicio(Nullable<int> idServicio)
        {
            var idServicioParameter = idServicio.HasValue ?
                new ObjectParameter("idServicio", idServicio) :
                new ObjectParameter("idServicio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("borrarServicio", idServicioParameter);
        }
    
        public virtual int borrarTipoAB(Nullable<int> idTipoAB)
        {
            var idTipoABParameter = idTipoAB.HasValue ?
                new ObjectParameter("idTipoAB", idTipoAB) :
                new ObjectParameter("idTipoAB", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("borrarTipoAB", idTipoABParameter);
        }
    
        public virtual int borrarTipoServicio(Nullable<int> idTipoServicio)
        {
            var idTipoServicioParameter = idTipoServicio.HasValue ?
                new ObjectParameter("idTipoServicio", idTipoServicio) :
                new ObjectParameter("idTipoServicio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("borrarTipoServicio", idTipoServicioParameter);
        }
    
        public virtual ObjectResult<buscarDetalleOrden_Result> buscarDetalleOrden(Nullable<int> idOrden)
        {
            var idOrdenParameter = idOrden.HasValue ?
                new ObjectParameter("idOrden", idOrden) :
                new ObjectParameter("idOrden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarDetalleOrden_Result>("buscarDetalleOrden", idOrdenParameter);
        }
    
        public virtual ObjectResult<buscarMesa_Result> buscarMesa(Nullable<int> idMesa)
        {
            var idMesaParameter = idMesa.HasValue ?
                new ObjectParameter("idMesa", idMesa) :
                new ObjectParameter("idMesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarMesa_Result>("buscarMesa", idMesaParameter);
        }
    
        public virtual ObjectResult<buscarOrden_Result> buscarOrden(Nullable<int> idOrden)
        {
            var idOrdenParameter = idOrden.HasValue ?
                new ObjectParameter("idOrden", idOrden) :
                new ObjectParameter("idOrden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarOrden_Result>("buscarOrden", idOrdenParameter);
        }
    
        public virtual ObjectResult<buscarServicio_Result> buscarServicio(Nullable<int> idServicio)
        {
            var idServicioParameter = idServicio.HasValue ?
                new ObjectParameter("idServicio", idServicio) :
                new ObjectParameter("idServicio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarServicio_Result>("buscarServicio", idServicioParameter);
        }
    
        public virtual ObjectResult<buscarTipoAB_Result> buscarTipoAB(Nullable<int> idTipoAB)
        {
            var idTipoABParameter = idTipoAB.HasValue ?
                new ObjectParameter("idTipoAB", idTipoAB) :
                new ObjectParameter("idTipoAB", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarTipoAB_Result>("buscarTipoAB", idTipoABParameter);
        }
    
        public virtual ObjectResult<buscarTipoServicio_Result> buscarTipoServicio(Nullable<int> idTipoServicio)
        {
            var idTipoServicioParameter = idTipoServicio.HasValue ?
                new ObjectParameter("idTipoServicio", idTipoServicio) :
                new ObjectParameter("idTipoServicio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarTipoServicio_Result>("buscarTipoServicio", idTipoServicioParameter);
        }
    
        public virtual int crearDetalleOrden(Nullable<int> idOrden, Nullable<int> idServicio, Nullable<int> cantidad)
        {
            var idOrdenParameter = idOrden.HasValue ?
                new ObjectParameter("idOrden", idOrden) :
                new ObjectParameter("idOrden", typeof(int));
    
            var idServicioParameter = idServicio.HasValue ?
                new ObjectParameter("idServicio", idServicio) :
                new ObjectParameter("idServicio", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crearDetalleOrden", idOrdenParameter, idServicioParameter, cantidadParameter);
        }
    
        public virtual int crearMesa(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crearMesa", nombreParameter);
        }
    
        public virtual int crearOrden(Nullable<int> idMesa, string descripcion, Nullable<System.DateTime> fecha)
        {
            var idMesaParameter = idMesa.HasValue ?
                new ObjectParameter("idMesa", idMesa) :
                new ObjectParameter("idMesa", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crearOrden", idMesaParameter, descripcionParameter, fechaParameter);
        }
    
        public virtual int crearServicio(Nullable<int> idTipoAB, Nullable<int> idTipoServicio, string nombre, string descripcion, Nullable<double> precio, Nullable<int> tiempo, string imagen)
        {
            var idTipoABParameter = idTipoAB.HasValue ?
                new ObjectParameter("idTipoAB", idTipoAB) :
                new ObjectParameter("idTipoAB", typeof(int));
    
            var idTipoServicioParameter = idTipoServicio.HasValue ?
                new ObjectParameter("idTipoServicio", idTipoServicio) :
                new ObjectParameter("idTipoServicio", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(double));
    
            var tiempoParameter = tiempo.HasValue ?
                new ObjectParameter("tiempo", tiempo) :
                new ObjectParameter("tiempo", typeof(int));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crearServicio", idTipoABParameter, idTipoServicioParameter, nombreParameter, descripcionParameter, precioParameter, tiempoParameter, imagenParameter);
        }
    
        public virtual int crearTipoAB(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crearTipoAB", nombreParameter);
        }
    
        public virtual int crearTipoServicio(Nullable<int> idTipoAB, string nombre)
        {
            var idTipoABParameter = idTipoAB.HasValue ?
                new ObjectParameter("idTipoAB", idTipoAB) :
                new ObjectParameter("idTipoAB", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crearTipoServicio", idTipoABParameter, nombreParameter);
        }
    
        public virtual int editarDetalleOrden(Nullable<int> idOrden, Nullable<int> idServicio, Nullable<int> cantidad)
        {
            var idOrdenParameter = idOrden.HasValue ?
                new ObjectParameter("idOrden", idOrden) :
                new ObjectParameter("idOrden", typeof(int));
    
            var idServicioParameter = idServicio.HasValue ?
                new ObjectParameter("idServicio", idServicio) :
                new ObjectParameter("idServicio", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editarDetalleOrden", idOrdenParameter, idServicioParameter, cantidadParameter);
        }
    
        public virtual int editarMesa(Nullable<int> idMesa, string nombre)
        {
            var idMesaParameter = idMesa.HasValue ?
                new ObjectParameter("idMesa", idMesa) :
                new ObjectParameter("idMesa", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editarMesa", idMesaParameter, nombreParameter);
        }
    
        public virtual int editarOrden(Nullable<int> idOrden, Nullable<int> idMesa, string descripcion, Nullable<System.DateTime> fecha)
        {
            var idOrdenParameter = idOrden.HasValue ?
                new ObjectParameter("idOrden", idOrden) :
                new ObjectParameter("idOrden", typeof(int));
    
            var idMesaParameter = idMesa.HasValue ?
                new ObjectParameter("idMesa", idMesa) :
                new ObjectParameter("idMesa", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editarOrden", idOrdenParameter, idMesaParameter, descripcionParameter, fechaParameter);
        }
    
        public virtual int editarServicio(Nullable<int> idServicio, Nullable<int> idTipoAB, Nullable<int> idTipoServicio, string nombre, string descripcion, Nullable<double> precio, Nullable<int> tiempo, string imagen)
        {
            var idServicioParameter = idServicio.HasValue ?
                new ObjectParameter("idServicio", idServicio) :
                new ObjectParameter("idServicio", typeof(int));
    
            var idTipoABParameter = idTipoAB.HasValue ?
                new ObjectParameter("idTipoAB", idTipoAB) :
                new ObjectParameter("idTipoAB", typeof(int));
    
            var idTipoServicioParameter = idTipoServicio.HasValue ?
                new ObjectParameter("idTipoServicio", idTipoServicio) :
                new ObjectParameter("idTipoServicio", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(double));
    
            var tiempoParameter = tiempo.HasValue ?
                new ObjectParameter("tiempo", tiempo) :
                new ObjectParameter("tiempo", typeof(int));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editarServicio", idServicioParameter, idTipoABParameter, idTipoServicioParameter, nombreParameter, descripcionParameter, precioParameter, tiempoParameter, imagenParameter);
        }
    
        public virtual int editarTipoAB(Nullable<int> idTipoAB, string nombre)
        {
            var idTipoABParameter = idTipoAB.HasValue ?
                new ObjectParameter("idTipoAB", idTipoAB) :
                new ObjectParameter("idTipoAB", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editarTipoAB", idTipoABParameter, nombreParameter);
        }
    
        public virtual int editarTipoServicio(Nullable<int> idTipoServicio, Nullable<int> idTipoAB, string nombre)
        {
            var idTipoServicioParameter = idTipoServicio.HasValue ?
                new ObjectParameter("idTipoServicio", idTipoServicio) :
                new ObjectParameter("idTipoServicio", typeof(int));
    
            var idTipoABParameter = idTipoAB.HasValue ?
                new ObjectParameter("idTipoAB", idTipoAB) :
                new ObjectParameter("idTipoAB", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editarTipoServicio", idTipoServicioParameter, idTipoABParameter, nombreParameter);
        }
    
        public virtual ObjectResult<verMesa_Result> verMesa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<verMesa_Result>("verMesa");
        }
    
        public virtual ObjectResult<verOrden_Result> verOrden()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<verOrden_Result>("verOrden");
        }
    
        public virtual ObjectResult<verServicio_Result> verServicio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<verServicio_Result>("verServicio");
        }
    
        public virtual ObjectResult<verTipoAB_Result> verTipoAB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<verTipoAB_Result>("verTipoAB");
        }
    
        public virtual ObjectResult<verTipoServicio_Result> verTipoServicio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<verTipoServicio_Result>("verTipoServicio");
        }
    }
}
